#!/bin/sh
export SRC=~/src
export CLOJURE_DIR=$SRC/clojure
export CLASSPATH=$CLASSPATH:$CLOJURE_DIR/clojure-contrib/clojure-contrib.jar:$CLOJURE_DIR/trunk/clojure.jar
export JARS=$SRC/jars
export RLWRAP=`which rlwrap`
export HERE=`pwd`

for file in $JARS/*.jar; do
    JARS=$JARS:$file
done

if [ -d $HERE/lib ]; then
    for file in $HERE/lib/*; do
        JARS=$JARS:$file
    done   
fi

if [ -d $HERE/src ]; then
  CLASSPATH=$CLASSPATH:src
fi

if [ -d $HERE/test ]; then
  CLASSPATH=$CLASSPATH:test
fi

CLASSPATH=$CLASSPATH:$JARS

if [ -z "$1" ]; then
    $RLWRAP java -cp $CLASSPATH clojure.main
else
    java -cp $CLASSPATH clojure.main $1
fi

