#!/bin/sh
export SRC=~/src
export CLOJURE_DIR=$SRC/clojure
export CLASSPATH=$CLASSPATH:$CLOJURE_DIR/clojure-contrib/clojure-contrib.jar:$CLOJURE_DIR/trunk/clojure.jar
export JARS=$SRC/jars
export HERE=`pwd`
export RLWRAP=`which rlwrap`
BREAK_CHARS="(){}[],^%$#@\"\";:''|\\"

for file in $JARS/*.jar; do
    JARS=$JARS:$file
done

if [ -d $HERE/lib ]; then
    for file in $HERE/lib/*; do
        JARS=$JARS:$file
    done   
fi

if [ -d $HERE/src ]; then
  CLASSPATH=$CLASSPATH:src
fi

CLASSPATH=$CLASSPATH$JARS

if [ -z "$1" ]; then
    $RLWRAP --remember -c -b $BREAK_CHARS -f $HOME/.clj_completions \
    java -cp $CLASSPATH clojure.main
else
    java -cp $CLASSPATH clojure.main $1    
fi

